# In this file I have all the general configurations and data

# environment/computational parameters
device: cuda
num_workers: 4

# dataset parameters
data_root: /home/rstofer/lst-super-res/

input_basemap: /home/rstofer/lst-super-res/For_CNN/inputs/RGB_672_10
input_target: /home/rstofer/lst-super-res/For_CNN/inputs/LST_672_70_10
output_target: /home/rstofer/lst-super-res/For_CNN/outputs/LST_672_10

splits_loc: /home/rstofer/lst-super-res/metadata/splits

target_norm_loc: /home/rstofer/lst-super-res/For_CNN/target_mean_sd_files672_70_10.txt
basemap_norm_loc: /home/rstofer/lst-super-res/For_CNN/basemap_mean_sd_files672_70_10.txt

# directory to save this experiment's models
experiment_dir: /home/rstofer/lst-super-res/experiments/base

# How many epochs have been completed already
epochs_done: 0

# model params
learning_rate: 1e-5
epochs: 50
batch_size: 1

# augmentation probabilities
HorizontalFlip: 0.5
VerticalFlip: 0.5
RandomRotate90: 0.5

# Calculate residuals
Residual: True

# OPTIONAL: pretrain
pretrain: True
pretrain_basemap: /home/rstofer/lst-super-res/For_pretrain/tiff
pretrain_splits_loc: /home/rstofer/lst-super-res/metadata/pretrain_splits
pretrain_basemap_norm_loc: /home/waves/projects/lst-super-res/For_pretrain/basemap_mean_sd_files.txt