# In this file I have all the general configurations and data

# environment/computational parameters
device: cuda
num_workers: 4

# dataset parameters
data_root: /Users/annaboser/Documents/GitHub/lst-super-res/data

input_basemap: /Users/annaboser/Documents/GitHub/lst-super-res/data/inputs/RGB_5
input_target: /Users/annaboser/Documents/GitHub/lst-super-res/data/inputs/LST_70_5
output_target: /Users/annaboser/Documents/GitHub/lst-super-res/data/outputs/LST_5

splits_loc: /Users/annaboser/Documents/GitHub/lst-super-res/data/metadata/splits

target_norm_loc: /Users/annaboser/Documents/GitHub/lst-super-res/data/metadata/normalizations/target_mean_sd_files70_5.txt
basemap_norm_loc: /Users/annaboser/Documents/GitHub/lst-super-res/data/metadata/normalizations/basemap_mean_sd_files70_5.txt