# In this file I have all the general configurations and data

# environment/computational parameters
device: cuda
num_workers: 4

# dataset parameters
data_root: /datadrive/For_CNN

input_basemap: /datadrive/For_CNN/inputs/RGB_672_10
input_target: /datadrive/For_CNN/inputs/LST_672_70_10
output_target: /datadrive/For_CNN/outputs/LST_672_10

splits_loc: /datadrive/For_CNN/metadata/splits

target_norm_loc: /datadrive/For_CNN/target_mean_sd_files672_70_10.txt
basemap_norm_loc: /datadrive/For_CNN/basemap_mean_sd_files672_70_10.txt

# augmentation probabilities
HorizontalFlip: 0.5
VerticalFlip: 0.5
GaussianNoise: 0.2
RandomRotate90: 0.5